In [10]:
import numpy as np

In [11]:
arr = np.random.rand(12, 13)

In [12]:
arr[0][0]

np.float64(0.1607327886965091)

In [13]:
print("STATS:")
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

STATS:
0.4898472945543836
0.9858406577400176
0.01636760814874394


In [14]:
np.mean(arr, axis=0).shape

(13,)

In [15]:
np.mean(arr, axis=1).shape

(12,)

In [21]:
# IT WILL CREATE A NEW OBJECT
line = np.arange(0, 16, 1)
arr2 = line.reshape(4,4)

print(arr2)

print("")
print("")
print("")

arr2[0][0] = 99
print(arr2)

print("")
print("")
print("")

print(line)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
